config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'

  root 'pages#index'
  get 'pages/help'

  resources :users
  resources :topics

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'

  post '/comments', to: 'comments#create'
end

app/models/animal.rb
class Animal
    
def type
    p "animal"
end

def bowbow
    p "鳴かない"
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < Animal
    def bowbow
      p "にゃー"
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :topic
end

app/models/dog.rb
class Dog < Animal

    def bowbow
      p "わん"
    end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments

  mount_uploader :image, ImageUploader

  def self.get_list(serch_params={}, order_param="new")
    topic = Topic.all.includes(:favorite_users)

    # 検索
    if serch_params.present?
      topic = topic.where(['title LIKE ?', "%#{serch_params[:title]}%"]) if serch_params[:title].present?
    end

    # ソート
    if order_param
      case order_param
      when "new"
        topic = topic.order(id: "DESC")
      when "old"
        topic = topic.order(id: "ASC")
      when "favolite"
        topic = topic.select('topics.*', 'count(favorites.id) AS favs').left_joins(:favorites).group('topics.id').order('favs desc')
      when "comment"
        topic = topic.select('topics.*', 'count(comments.id) AS coms').left_joins(:comments).group('topics.id').order('coms desc')
      end
    end
    
    topic
  end
end

app/models/usagi.rb
class Usagi < Animal


end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }
    validates :password, length: { in: 8..32}
    has_secure_password

    has_many :topics
    has_many :favorites
    has_many :favorite_topics, through: :favorites, source: 'topic'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    add_flash_types :success, :info, :warning, :danger
  
    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !current_user.nil?
    end

    def redirect_index
        redirect_to topics_path if logged_in?
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @topic = Topic.find_by(id: comment_params[:topic_id])
        @comment = @topic.comments.build(comment_params)
        @comment.save
        
        # if comment.save
        #     redirect_to topics_path, success: 'コメントを追加しました'
        # else
        #     redirect_to topics_path, warning: 'コメントを追加に失敗しました'
        # end
    end

    private
    def comment_params
        params.require(:comment).permit(:body, :topic_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def index
      @favorite_topics = current_user.favorite_topics
    end
  
    def create
      favorite = Favorite.new
      favorite.user_id = current_user.id
      favorite.topic_id = params[:topic_id]
  
      if favorite.save
        redirect_to topics_path, success: 'お気に入りに登録しました'
      else
        redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
      end
    end

    def destroy
        topic = Topic.find_by(id: params[:topic_id])
        favorite = topic.favorites.find_by(user_id: current_user.id)
        if favorite.destroy
            redirect_to topics_path, success: 'お気に入りに解除しました'
          else
            redirect_to topics_path, danger: 'お気に入りに解除に失敗しました'
          end
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :redirect_index, only: [:index]

  def index
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in(user)
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    session[:order_param]   = order_param
    session[:search_params] = search_params

    @topics = Topic.get_list(search_params, order_param)
    @topics = @topics.page(params[:page]).per(5)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description, :title)
  end

  def order_param
    params[:order].present? ? params[:order] : session[:order_param]
  end

  def search_params
    params[:search].present? ? params[:search] : session[:search_params]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
          
            <h4 class="topic-author">
              <%= topic.title.present? ? topic.title : "タイトルなし" %>
            </h4>

            <%= image_tag topic.image.url %>

            <div class="inner-row">
              <div class="topic-author">
                投稿者　：<%= topic.user.name %>
              </div>
              <div class="topic-createddate">
                投稿日時：<%= topic.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
              </div>
            </div>

            <div class="inner-row">
              <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <i class="far fa-heart fa-2x topic-index-icon"></i>
              <% end %>
              <% else %>
                <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                  <i class="fas fa-heart fa-2x topic-index-icon"></i>
                <% end %>
              <% end %>
              <label>
                <%= topic.favorite_users.count %>
              </label>        
              <%= image_tag 'icons/comment.png', class: 'add-comment topic-index-icon' %>
            </div>

            <p class="topic-text">
              <%= topic.description %>
            </p>

            <div class="comment-area">
              <h4 class="comment-title">コメント</h4>
              <% comments = topic.comments %>
               <div class="comment-body-area">
                <% if comments.present? %>
                  <% comments.each do |comment| %>
                    <p class="comment-body">
                      <%= comment.body %>
                    </p>
                  <% end %>
                <% else %>
                  <p class="comment-body">
                  <%= "コメントはありません" %>
                </p>
                <% end %>
               </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/_comment.html.erb
<h4 class="comment-title">コメント</h4>
<% comments = topic.comments %>
<div class="comment-body-area">
<% if comments.present? %>
    <% comments.each do |comment| %>
    <p class="comment-body">
        <%= comment.body %>
    </p>
    <% end %>
    <div class="more">
        <p>
            さらに表示...
        </p>
    </div>
    
<% else %>
    <p class="comment-body">
        <%= "コメントはありません" %>
    </p>
<% end %>
</div>

<%= form_for Comment.new, remote: true do |f| %>
<div class="form-group comment-form">
    <%= f.text_area :body, class: 'form-control' %>
    <%= f.submit 'コメントする', id: "comment_submit", class: 'btn btn-black btn-block', disabled: "disabled"%>
    <%= f.hidden_field :topic_id, :value => topic.id %>
</div>
<% end %>

app/views/topics/index.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" display="none">
  <symbol id="search" viewBox="0 0 32 32">
    <path d="M 19.5 3 C 14.26514 3 10 7.2651394 10 12.5 C 10 14.749977 10.810825 16.807458 12.125 18.4375 L 3.28125 27.28125 L 4.71875 28.71875 L 13.5625 19.875 C 15.192542 21.189175 17.250023 22 19.5 22 C 24.73486 22 29 17.73486 29 12.5 C 29 7.2651394 24.73486 3 19.5 3 z M 19.5 5 C 23.65398 5 27 8.3460198 27 12.5 C 27 16.65398 23.65398 20 19.5 20 C 15.34602 20 12 16.65398 12 12.5 C 12 8.3460198 15.34602 5 19.5 5 z" />
  </symbol>
</svg>

<div class="side-menu" > 
  <div class="inner-menu">
    <div class="search-form-area">

      <%= form_with url: topics_path, method: :get, local: true, class: "search-form" do |f| %>
        <%= f.text_field "search[title]", :value => session[:search_params][:title], :placeholder => "Title", :class => "search-input" %>
        <button type="submit" class="search-button">
          <svg class="submit-button">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#search"></use>
          </svg>
        </button>
      <% end %>
    </div>

    <div id="wrap">
        <ul class="order-list delay-show">
          <li>
            <%= link_to "新着順", topics_path(order: "new"), class: session[:order_param] == "new" || session[:order_param].blank? ? 'active' : "" %>
          </li>
          <li>
            <%= link_to "古い順", topics_path(order: "old"), class: session[:order_param] == "old" ? 'active' : "" %>
          </li>
          <li>
            <%= link_to "いいねの多い順", topics_path(order: "favolite"), class: session[:order_param] == "favolite" ? 'active' : "" %>
          </li>
          <li>
            <%= link_to "コメントの多い順", topics_path(order: "comment"), class: session[:order_param] == "comment" ? 'active' : "" %>
          </li>
        </ul>
      </div>
      <div id="pagenate">
        <%= paginate @topics %>
      </div>
  </div>
</div>


<div class="topic-index-wrapper">
  <div class="container">
    <% if @topics.present? %>
      <% @topics.each do |topic| %>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="topic-index-single">
            
              <h4 class="topic-author">
                <%= topic.title.present? ? topic.title : "タイトルなし" %>
              </h4>

              <%= image_tag topic.image.url %>

              <div class="inner-row">
                <div class="topic-author">
                  投稿者　：<%= topic.user.name %>
                </div>
                <div class="topic-createddate">
                  投稿日時：<%= topic.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                </div>
              </div>

              <div class="inner-row">
                <% if !topic.favorite_users.include?(current_user) %>
                  <%= link_to favorites_path(topic_id: topic.id), class: 'add-favorite', method: :post do %>
                    <i class="far fa-heart fa-2x topic-index-icon add-fa vorite"></i>
                  <% end %>
                <% else %>
                  <%= link_to favorites_path(topic_id: topic.id), class: 'add-favorite', method: :delete do %>
                    <i class="fas fa-heart fa-2x topic-index-icon add-favorite"></i>
                  <% end %>
                <% end %>
                <label id="favorite_count">
                  <%= topic.favorite_users.count %>
                </label>        
                
                
                <i class="fas fa-comment fa-2x topic-index-icon add-comment"></i>
                
                <label id=<%= "comment_count_#{topic.id}" %>>
                  <%= topic.comments.count %>
                </label>   
              </div>

              <p class="topic-text">
                <%= topic.description %>
              </p>

              <div class="comment-area" id=<%= "topic_comment_#{topic.id}" %>>
                <%= render "comment", topic: topic %>
              </div>

            </div>
          </div>
        </div>
      <% end %>
    <% else %>
    
    <% end %>

    
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %> 
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>