config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'

  root 'pages#index'
  get 'pages/help'

  resources :users
  resources :topics

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'

  post '/comments', to: 'comments#create'
end

app/models/animal.rb
class Animal
    
def type
    p "animal"
end

def bowbow
    p "鳴かない"
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < Animal
    def bowbow
      p "にゃー"
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :topic
end

app/models/dog.rb
class Dog < Animal

    def bowbow
      p "わん"
    end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments

  mount_uploader :image, ImageUploader

  def self.get_list(serch_params={}, order_param="new")
    topic = Topic.all.includes(:favorite_users)

    # 検索
    if serch_params.present?
      topic = topic.where(['title LIKE ?', "%#{serch_params[:title]}%"]) if serch_params[:title].present?
    end

    # ソート
    if order_param
      case order_param
      when "new"
        topic = topic.order(id: "DESC")
      when "old"
        topic = topic.order(id: "ASC")
      when "favolite"
        topic = topic.select('topics.*', 'count(favorites.id) AS favs').left_joins(:favorites).group('topics.id').order('favs desc')
      when "comment"
        topic = topic.select('topics.*', 'count(comments.id) AS coms').left_joins(:comments).group('topics.id').order('coms desc')
      end
    end
    
    topic
  end
end

app/models/usagi.rb
class Usagi < Animal


end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }
    validates :password, length: { in: 8..32}
    has_secure_password

    has_many :topics
    has_many :favorites
    has_many :favorite_topics, through: :favorites, source: 'topic'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @topic = Topic.find_by(id: comment_params[:topic_id])
        @comment = @topic.comments.build(comment_params)
        @comment.save
        
        # if comment.save
        #     redirect_to topics_path, success: 'コメントを追加しました'
        # else
        #     redirect_to topics_path, warning: 'コメントを追加に失敗しました'
        # end
    end

    private
    def comment_params
        params.require(:comment).permit(:body, :topic_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :redirect_index, only: [:index]

  def index
  end

  def help
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    session[:order_param]   = order_param
    session[:search_params] = search_params

    @topics = Topic.get_list(search_params, order_param)
    @topics = @topics.page(params[:page]).per(5)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description, :title)
  end

  def order_param
    params[:order].present? ? params[:order] : session[:order_param]
  end

  def search_params
    params[:search].present? ? params[:search] : session[:search_params]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

   <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <li>
                <%= link_to favorites_index_path do %>
                  <%= image_tag 'icons/heart.png' %>
                <% end %>
              </li>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag 'icons/camera.png' %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>